import React from 'react';
import { IoCaretUpOutline, IoCaretDownOutline , IoChevronForwardOutline,IoChevronBackOutline, IoCloseOutline, IoCardOutline, IoWalletOutline, IoTrendingDownOutline, IoTrendingUpOutline, IoStarSharp, IoSearchOutline, IoSwapHorizontalOutline, IoCashOutline, IoSwapVerticalOutline, IoAddOutline, IoRemoveOutline, IoSyncOutline, IoEllipsisVerticalOutline, IoLinkOutline, IoOpenOutline, IoPersonOutline, IoChatboxOutline, IoDocumentTextOutline, IoCopyOutline, IoCheckmarkOutline, IoCodeSlashOutline, IoServerOutline, IoPencilOutline, IoShieldCheckmarkOutline, IoPeopleOutline, IoEyeOutline, IoBagCheckOutline, IoHeartOutline, IoPricetagOutline } from 'react-icons/io5';
import { AiOutlineBank } from 'react-icons/ai';

export const icons = {
  up_icon: <IoCaretUpOutline className="icon"/>,
  down_icon: <IoCaretDownOutline className="icon"/>,
  forward_icon: <IoChevronForwardOutline className="icon"/>,
  back_icon: <IoChevronBackOutline className="icon"/>,
  close_icon: <IoCloseOutline className="icon"/>,
  credit_card_icon: <IoCardOutline className="icon"/>,
  wallet_icon: <IoWalletOutline className="icon"/>,
  trending_down_icon: <IoTrendingDownOutline className="icon"/>,
  trending_up_icon: <IoTrendingUpOutline className="icon"/>,
  star_icon: <IoStarSharp className="icon"/>,
  search_icon: <IoSearchOutline className="icon"/>,
  change_horizontal_icon: <IoSwapHorizontalOutline  className="icon"/>,
  change_vertical_icon: <IoSwapVerticalOutline  className="icon"/>,
  bank_icon: <AiOutlineBank  className="icon"/>,
  cash_icon: <IoCashOutline  className="icon"/>,
  add_icon: <IoAddOutline  className="icon"/>,
  remove_icon: <IoRemoveOutline  className="icon"/>,
  convert_icon: <IoSyncOutline  className="icon"/>,
  dots_vertical_icon: <IoEllipsisVerticalOutline  className="icon"/>,
  link_icon: <IoLinkOutline  className="icon"/>,
  open_icon: <IoOpenOutline  className="icon"/>,
  person_icon: <IoPersonOutline  className="icon"/>,
  chat_icon: <IoChatboxOutline  className="icon"/>,
  document_icon: <IoDocumentTextOutline  className="icon"/>,
  copy_icon: <IoCopyOutline  className="icon"/>,
  check_icon: <IoCheckmarkOutline  className="icon"/>,
  source_icon: <IoCodeSlashOutline  className="icon"/>,
  server_icon: <IoServerOutline  className="icon"/>,
  pencil_icon: <IoPencilOutline  className="icon"/>,
  check_icon: <IoShieldCheckmarkOutline  className="icon"/>,
  people_icon: <IoPeopleOutline  className="icon"/>,
  eye_icon: <IoEyeOutline  className="icon"/>,
  bag_icon: <IoBagCheckOutline  className="icon"/>,
  heart_icon: <IoHeartOutline  className="icon"/>,
  tag_icon: <IoPricetagOutline  className="icon"/>,
}